# Generated by Django 5.0.14 on 2025-09-09 23:05

import cloudinary.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_remove_product_image_productimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="banner",
            name="button_text",
            field=models.CharField(default="Buy now", max_length=50),
        ),
        migrations.AddField(
            model_name="banner",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="banner",
            name="discount_text",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="banner",
            name="image_mobile",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image_mobile"
            ),
        ),
        migrations.AddField(
            model_name="banner",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="banner",
            name="secondary_image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="secondary_image"
            ),
        ),
        migrations.AddField(
            model_name="banner",
            name="subtitle",
            field=models.TextField(blank=True, null=True),
        ),
    ]
