# Generated by Django 5.0.14 on 2025-09-20 16:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_banner_button_text_banner_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="colors",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=50),
                blank=True,
                default=list,
                help_text="List of available colors, e.g. ['Red', 'Blue', 'Black']",
                size=None,
            ),
        ),
    ]
