# Generated by Django 5.0.14 on 2025-09-25 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_cart_cartitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="color",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
