# Generated by Django 5.0.14 on 2025-09-25 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_cartitem_color"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together={("cart", "product", "color")},
        ),
    ]
