# Generated by Django 5.0.14 on 2025-10-03 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0013_alter_address_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_seller",
            field=models.BooleanField(default=True),
        ),
    ]
